#!/bin/bash

# Get the version of the binary from sbt and strip color information so we are just left with a version
SBT_VERSION=`sbt version | tail -1 | awk {'print $2'} | sed -E "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"`
echo VERSION = "Building RPM for version: $SBT_VERSION"

RPM_VERSION="$(date +'%Y%m%d%H%M%S')"
RPM_NAME="os-address-lookup"
RPM_OWNER="jenkins@dvla"
RPM_DESCRIPTION="Ordnance Survey Address Lookup"
RPM_URL="http://example.dotcom.com"
RPM_LICENSE="MIT"
RPM_VENDOR="DVLA"
RPM_PREFIX="/opt/os-address-lookup/"
RPM_TARGETDIR="$WORKSPACE/target/" #grab the jenkins WORKSPACE working dir
MONIT_FILES_DIR="monit/"
UPSTART_FILES_DIR="upstart/"
DEPENDS="monit"
test -z WORKSPACE || export WORKSPACE=$PWD

echo *********************************
echo
echo Creating RPM
echo
echo *********************************

# this is really ugly, refactor all of this
# create workdir directories
rm -rf ./workdir
mkdir -p workdir/$RPM_PREFIX
mkdir -p workdir/etc/init
mkdir -p workdir/etc/monit.d

# copy objects to workdir directory
(
  cd workdir/$RPM_PREFIX/
  cp  $WORKSPACE/target/scala-2.10/*-assembly-${SBT_VERSION}.jar os-address-lookup.jar
  cd -
)

# add the init files
cp -r $MONIT_FILES_DIR/* workdir/etc/monit.d
cp -r $UPSTART_FILES_DIR/* workdir/etc/init

# add application.conf
cp $WORKSPACE/target/scala-2.10/classes/application.conf workdir/$RPM_PREFIX/

# add a git log file
git log > workdir/$RPM_PREFIX/git-log.txt

#and the pkg pre/post install scripts

# package the thing
test -e $RPM_TARGETDIR || mkdir $RPM_TARGETDIR
fpm \
  --before-remove="pkg-scripts/stop" \
  --after-install="pkg-scripts/restart" \
  --description="$RPM_DESCRIPTION" \
  --url=$RPM_URL \
  --license="$RPM_LICENSE" \
  --vendor="$RPM_VENDOR" \
  -n $RPM_NAME \
  -v $RPM_VERSION  \
  -a all \
  -p $RPM_TARGETDIR/$RPM_NAME.rpm \
  -m $RPM_OWNER \
  -x "*.rpm" -x .git -x .gitignore \
  -t rpm \
  -d "$DEPENDS" \
  -C workdir \
  -s dir .

# Versioning, stage 1
rm -rf $WORKSPACE/target2/*.rpm
mkdir -p $WORKSPACE/target2
cp $WORKSPACE/target/$RPM_NAME.rpm $WORKSPACE/target2/$RPM_NAME-$SBT_VERSION-$BUILD_NUMBER.rpm
ln -s $WORKSPACE/target2/$RPM_NAME-$SBT_VERSION-$BUILD_NUMBER.rpm $WORKSPACE/target2/$RPM_NAME-latest.rpm
ln -s $WORKSPACE/target2/$RPM_NAME-$SBT_VERSION-$BUILD_NUMBER.rpm $WORKSPACE/target2/$RPM_NAME-latest-$BRANCH_TO_BUILD.rpm

