- name: install unzip
  yum: name=unzip

- name: install rubygems
  yum: name=rubygems

- name: install ruby-devel
  yum: name=ruby-devel

- name: task_description
  command: gem install sass
    creates=/usr/bin/sass
  tags:
    - sass

- name: task_description
  command: gem install fpm
    creates=/usr/bin/fpm
  tags:
    - fpm

- name: install rpm-build
  yum: name=rpm-build

- name: install java-1.7.0-openjdk
  yum: name=java-1.7.0-openjdk

- name: install java-1.7.0-openjdk-devel
  yum: name=java-1.7.0-openjdk-devel

- name: install fpm
  gem: name=fpm state=present

- name: get sbt
  get_url: dest=/tmp/sbt.rpm url=http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt//0.13.1/sbt.rpm

- name: install sbt
  command: yum localinstall /tmp/sbt.rpm -y
    creates=/usr/bin/sbt

- name: sbt clean
  command: sbt clean
    chdir=/vagrant
  tags:
    - sbt-clean

- name: sbt assembly
  command: sbt assembly
    chdir=/vagrant
  tags:
    - sbt-dist

