- name: install git
  action: yum name=git state=latest

- name: install openssl
  action: yum name=openssl state=present

- name: install DVLA secrets
  git: repo={{ GIT_REMOTE_STRING }} dest=/etc/DVLA/secrets version=HEAD

- name: create conf directory for vehicles-secrets
  file: path=/opt/qas-address-lookup state=directory

- name: Decrypt vehiclesServices.conf
  shell: /etc/DVLA/secrets/decrypt-file /etc/DVLA/secrets/ms/dev/vehiclesServices.conf.enc /opt/qas-address-lookup/vehiclesServices.conf {{ GIT_SECRET_PASSPHRASE }}

